i = int(input())
l = list(map(int,input().split()))
even = len([x for x in l if x%2 == 0])
odd = len([x for x in l if x%2 == 1])
positive = len([x for x in l if x>0])
negative = len([x for x in l if x<0])
print(f'Even: {even}')
print(f'Odd: {odd}')
print(f'Positive: {positive}')
print(f'Negative: {negative}')
